using NLog;
using System.Linq;
using WorldRank.Application;
using WorldRank.Application.Strategies;
using WorldRank.Console;
using WorldRank.Domain;
using WorldRank.Domain.Entities;
using WorldRank.Domain.Enums;
using WorldRank.Domain.Exceptions;
using WorldRank.Infrastructure;


var logger = LogManager.GetCurrentClassLogger();

//Wallets are stored in their own repository and reference the player via PlayerId
IWalletRepository walletRepository = new InMemoryWalletRepository();
IPlayerRepository playerRepository = new InMemoryPlayerRepository();

IFundsStrategy strategy = new AddFundsStrategy();
logger.Info("Application started.");

while (true)
{
	Console.WriteLine("\n=== WorldRank Player Registry ===");
	Console.WriteLine("--- Players ---");
	Console.WriteLine("1. Add player");
	Console.WriteLine("2. List all players");
	Console.WriteLine("3. List players grouped by score");
	Console.WriteLine("4. Find player by name");
	Console.WriteLine("5. Find player by id");
	Console.WriteLine("6. Delete player");
	Console.WriteLine("--- Wallets ---");
	Console.WriteLine("7. Add wallet to player");
	Console.WriteLine("8. Show player wallets");
	Console.WriteLine("9. Deposit to wallet");
	Console.WriteLine("10. Withdraw from wallet");
	Console.WriteLine("11. Block wallet");
	Console.WriteLine("12. Unblock wallet");
	Console.WriteLine("13. Update wallet balance");
	Console.WriteLine("0. Exit");
	Console.Write("> ");

	Action? action = Console.ReadLine() switch
	{
		"1" => AddPlayer,
		"2" => ListPlayers,
		"3" => ListPlayersByScore,
		"4" => FindPlayerByName,
		"5" => FindPlayerById,
		"6" => DeletePlayer,
		"7" => AddWalletToPlayer,
		"8" => GetWalletsOfPlayer,
		"9" => DepositToWallet,
		"10" => WithdrawFromWallet,
		"11" => BlockWallet,
		"12" => UnblockWallet,
		"13" => UpdateWalletBalance,
		"0" => null,
		_ => () => Console.WriteLine("Unknown option.")
	};

	if (action is null)
	{
		logger.Info("Application exiting.");
		LogManager.Shutdown(); // flush file writes before exit
		return; // "0" selected — exit
	}

	try
	{
		action();
	}
	catch (Exception ex)
	{
		// Safety net: log any exception the specific handlers did not catch, and keep the app running.
		logger.Error(ex, "Unexpected error while handling a menu action");
		Console.WriteLine($"Unexpected error: {ex.Message}");
	}
}

#region Input Helpers

Guid? PromptPlayerId()
{
	Console.Write("Give player id (guid): ");
	if (Guid.TryParse(Console.ReadLine(), out var playerId))
		return playerId;

	Console.WriteLine("Player id must be a GUID.");
	return null;
}

Currency? PromptCurrency()
{
	Console.Write("Give Currency: 1 - EUR | 2 - USD\n");
	switch (Console.ReadLine())
	{
		case "1":
			return Currency.EUR;
		case "2":
			return Currency.USD;
		default:
			Console.WriteLine("Unknown currency.");
			return null;
	}
}

decimal? PromptAmount(string label)
{
	Console.Write($"{label}: ");
	if (decimal.TryParse(Console.ReadLine(), out var amount))
		return amount;

	Console.WriteLine("Amount must be a number.");
	return null;
}

// Generates a random, unique player id (avoids collisions with already-registered players).
// Player.Id is a GUID generated by the Player constructor; no manual id generation needed.


// Runs a wallet operation and turns any domain (WalletException) failure into a friendly message + log.
void RunWalletOperation(Action operation)
{
	try
	{
		operation();
	}
	catch (WalletException ex)
	{
		logger.Warn(ex, "Wallet operation failed");
		Console.WriteLine($"Error: {ex.Message}");
	}
}

#endregion Input Helpers

#region Player Methods

void AddPlayer()
{
	Console.Write("Name: ");
	var name = Console.ReadLine();
	if (string.IsNullOrWhiteSpace(name))
	{
		Console.WriteLine("Name cannot be empty.");
		return;
	}

	Console.Write("Score: ");
	var scoreInput = Console.ReadLine();
	if (!int.TryParse(scoreInput, out var score))
	{
		Console.WriteLine("Score must be a whole number.");
		return;
	}

	var player = new Player(name);
	player.UpdateScore(score);
	playerRepository.AddAsync(player).GetAwaiter().GetResult();
	Console.WriteLine($"Player added successfully. Id: {player.Id}");
}

void ListPlayers()
{
	var all = playerRepository.GetAllAsync().GetAwaiter().GetResult().ToList();

	if (all.Count == 0)
	{
		Console.WriteLine("No players registered.");
		return;
	}

	foreach (var player in all)
		Console.WriteLine(player);
}

void ListPlayersByScore()
{
	var all = playerRepository.GetAllAsync().GetAwaiter().GetResult();
	var groups = all.GroupBy(p => p.Score).OrderBy(g => g.Key).ToList();

	if (groups.Count == 0)
	{
		Console.WriteLine("No players registered.");
		return;
	}

	foreach (var group in groups)
	{
		Console.WriteLine($"Score {group.Key}:");
		foreach (var player in group)
			Console.WriteLine($"  {player}");
	}
}

void FindPlayerByName()
{
	Console.Write("Search by name: ");
	var term = Console.ReadLine() ?? string.Empty;

	var player = playerRepository.GetByNameAsync(term).GetAwaiter().GetResult();

	Console.WriteLine(player is null ? "No player found." : player.ToString());
}

void FindPlayerById()
{
	var playerId = PromptPlayerId();
	if (playerId is null)
		return;

	var player = playerRepository.GetByIdAsync(playerId.Value).GetAwaiter().GetResult();

	Console.WriteLine(player is null ? "No player found." : player.ToString());
}

void DeletePlayer()
{
	var playerId = PromptPlayerId();
	if (playerId is null)
		return;

	playerRepository.DeleteAsync(playerId.Value).GetAwaiter().GetResult();
	Console.WriteLine("Player deleted (if it existed).");
}

#endregion Player Methods

#region Wallet Methods

void AddWalletToPlayer()
{
	var playerId = PromptPlayerId();
	if (playerId is null)
		return;

	var currency = PromptCurrency();
	if (currency is null)
		return;

	var balance = PromptAmount("Initial balance");
	if (balance is null)
		return;

	try
	{
		if (playerRepository.GetByIdAsync(playerId.Value).GetAwaiter().GetResult() is null)
			throw new PlayerNotFoundException(playerId.Value);

		var wallet = new Wallet(playerId.Value, currency.Value);
		if (balance.Value > 0)
			wallet.Deposit(balance.Value);

		walletRepository.AddAsync(wallet).GetAwaiter().GetResult();
		Console.WriteLine("Wallet added successfully.");
	}
	catch (PlayerNotFoundException ex)
	{
		logger.Warn(ex, "Could not add wallet, player {PlayerId} not found", playerId);
		Console.WriteLine($"Error: {ex.Message}");
	}
	catch (WalletException ex)
	{
		logger.Warn(ex, "Could not add wallet for player {PlayerId} in {Currency}", playerId, currency);
		Console.WriteLine($"Error: {ex.Message}");
	}
}

void GetWalletsOfPlayer()
{
	var playerId = PromptPlayerId();
	if (playerId is null)
		return;

	var wallets = walletRepository.GetByPlayerAsync(playerId.Value).GetAwaiter().GetResult().ToList();

	if (wallets.Count == 0)
	{
		Console.WriteLine("No wallets found for this player.");
		return;
	}

	foreach (var wallet in wallets)
		Console.WriteLine($"Wallet Number {wallets.IndexOf(wallet)} {wallet}");
}

void DepositToWallet()
{
	var playerId = PromptPlayerId();
	if (playerId is null)
		return;

	var currency = PromptCurrency();
	if (currency is null)
		return;

	var amount = PromptAmount("Amount to deposit");
	if (amount is null)
		return;

	RunWalletOperation(() =>
	{
		var wallets = walletRepository.GetByPlayerAsync(playerId.Value).GetAwaiter().GetResult();
		var wallet = wallets.FirstOrDefault(w => w.Currency == currency.Value);
		if (wallet is null)
			throw new WalletNotFoundException(playerId.Value, currency.Value);

		wallet.Deposit(amount.Value);
		walletRepository.SaveChangesAsync().GetAwaiter().GetResult();
		Console.WriteLine("Deposit successful.");
	});
}

void WithdrawFromWallet()
{
	var playerId = PromptPlayerId();
	if (playerId is null)
		return;

	var currency = PromptCurrency();
	if (currency is null)
		return;

	var amount = PromptAmount("Amount to withdraw");
	if (amount is null)
		return;

	RunWalletOperation(() =>
	{
		var wallets = walletRepository.GetByPlayerAsync(playerId.Value).GetAwaiter().GetResult();
		var wallet = wallets.FirstOrDefault(w => w.Currency == currency.Value);
		if (wallet is null)
			throw new WalletNotFoundException(playerId.Value, currency.Value);

		wallet.Withdraw(amount.Value);
		walletRepository.SaveChangesAsync().GetAwaiter().GetResult();
		Console.WriteLine("Withdrawal successful.");
	});
}

void BlockWallet()
{
	var playerId = PromptPlayerId();
	if (playerId is null)
		return;

	var currency = PromptCurrency();
	if (currency is null)
		return;

	RunWalletOperation(() =>
	{
		var wallets = walletRepository.GetByPlayerAsync(playerId.Value).GetAwaiter().GetResult();
		var wallet = wallets.FirstOrDefault(w => w.Currency == currency.Value);
		if (wallet is null)
			throw new WalletNotFoundException(playerId.Value, currency.Value);

		wallet.Block();
		walletRepository.SaveChangesAsync().GetAwaiter().GetResult();
		Console.WriteLine("Wallet blocked.");
	});
}

void UnblockWallet()
{
	var playerId = PromptPlayerId();
	if (playerId is null)
		return;

	var currency = PromptCurrency();
	if (currency is null)
		return;

	RunWalletOperation(() =>
	{
		var wallets = walletRepository.GetByPlayerAsync(playerId.Value).GetAwaiter().GetResult();
		var wallet = wallets.FirstOrDefault(w => w.Currency == currency.Value);
		if (wallet is null)
			throw new WalletNotFoundException(playerId.Value, currency.Value);

		wallet.Unblock();
		walletRepository.SaveChangesAsync().GetAwaiter().GetResult();
		Console.WriteLine("Wallet unblocked.");
	});
}

void UpdateWalletBalance()
{
	var playerId = PromptPlayerId();
	if (playerId is null)
		return;

	var currency = PromptCurrency();
	if (currency is null)
		return;

	var newBalance = PromptAmount("New balance");
	if (newBalance is null)
		return;

	RunWalletOperation(() =>
	{
		var wallets = walletRepository.GetByPlayerAsync(playerId.Value).GetAwaiter().GetResult();
		var wallet = wallets.FirstOrDefault(w => w.Currency == currency.Value);
		if (wallet is null)
			throw new WalletNotFoundException(playerId.Value, currency.Value);

		var diff = newBalance.Value - wallet.Balance;
		if (diff > 0)
			wallet.Deposit(diff);
		else if (diff < 0)
			wallet.ForceWithdraw(-diff);

		walletRepository.SaveChangesAsync().GetAwaiter().GetResult();
		Console.WriteLine("Balance updated.");
	});
}

#endregion Wallet Methods
